import os

SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))

CONTENT_URL = "https://habitica.com/api/v3/content"

def downloadJson(url):
    import urllib.request
    import json
    with urllib.request.urlopen(url) as response:
        data = json.loads(response.read().decode())
    return data


def updateContentKeys():
    json_data = downloadJson(CONTENT_URL)
    content_keys = json_data['data'].keys()
    print("Found %d content keys" % len(content_keys))
    for key in content_keys:
        print("   %s" % key)

    out_file = os.path.join(SCRIPT_DIR, "ContentKeys.ts")

    with open(out_file, "w") as f:
        f.write("// This file is auto-generated by scriptUpdateContentKeys.py\n")
        f.write("// It contains the list of content keys available in Habitica\n")
        f.write("// It is used to filter the huge content object returned by the API\n")

        f.write("export const contentKeys = [\n")
        for key in content_keys:
            f.write(f"    '{key}',\n")
        f.write("];\n")


if __name__ == "__main__":
    updateContentKeys()
